# Generated by Django 3.2.8 on 2021-10-26 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Traceability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('seed_type', models.CharField(choices=[('Criolla', 'Criolla'), ('Mejorada', 'Mejorada'), ('Baby', 'Baby'), ('Hibrida', 'Hibrida')], max_length=30, verbose_name='Tipo de Semilla')),
                ('crop_type', models.CharField(choices=[('Invernadero', 'Invernadero'), ('Ambiente Libre', 'Ambiente Libre'), ('Organico', 'Organico')], max_length=30, verbose_name='Tipo de Cultivo')),
                ('geo_zone', models.CharField(max_length=50, verbose_name='Zona Geografica')),
                ('plant_size', models.SmallIntegerField(verbose_name='Tamaño de la planta (cm)')),
                ('leaves_size', models.SmallIntegerField(verbose_name='Tamaño de las hojas (cm)')),
                ('flowers_size', models.SmallIntegerField(verbose_name='Tamaño de las flores (cm)')),
                ('taxonomic', models.CharField(max_length=100, verbose_name='Clasificación Taxonomica')),
                ('date_collection', models.DateField(verbose_name='Fecha de Recolección')),
                ('reception_date', models.DateField(verbose_name='Fecha de Ingreso')),
                ('weight_collection', models.SmallIntegerField(verbose_name='Peso de Material Recolectado (Kg)')),
                ('accepted_material', models.SmallIntegerField(verbose_name='Peso de Material Aceptado (Kg)')),
                ('classification_date', models.DateField(verbose_name='Fecha de Clasificación')),
                ('control_number', models.CharField(max_length=15, verbose_name='N° de Control')),
                ('batch_number', models.CharField(max_length=15, verbose_name='N° de Lote de Material Vegetal')),
                ('extract_batch_number', models.CharField(max_length=15, verbose_name='N° de Lote de Extracto')),
                ('extraction_date', models.DateField(verbose_name='Fecha de Extracción')),
                ('conc_batch_number', models.CharField(max_length=15, verbose_name='N° de Lote de Concentrado')),
                ('conc_date', models.DateField(verbose_name='Fecha de Concentración')),
                ('isolate_batch_number', models.CharField(max_length=15, verbose_name='N° de Lote de Aislado')),
                ('isolate_date', models.DateField(verbose_name='Fecha de Aislamiento')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traceable_traceability_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traceable_traceability_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Traceability',
                'verbose_name_plural': 'Traceabilitys',
                'db_table': 'Traceability',
            },
        ),
    ]
