# Generated by Django 3.2.8 on 2021-10-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traceable', '0002_alter_traceability_accepted_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traceability',
            name='batch_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='N° de Lote de Material Vegetal'),
        ),
        migrations.AlterField(
            model_name='traceability',
            name='classification_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Clasificación'),
        ),
        migrations.AlterField(
            model_name='traceability',
            name='conc_batch_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='N° de Lote de Concentrado'),
        ),
        migrations.AlterField(
            model_name='traceability',
            name='conc_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Concentración'),
        ),
        migrations.AlterField(
            model_name='traceability',
            name='control_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='N° de Control'),
        ),
        migrations.AlterField(
            model_name='traceability',
            name='extract_batch_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='N° de Lote de Extracto'),
        ),
        migrations.AlterField(
            model_name='traceability',
            name='extraction_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Extracción'),
        ),
        migrations.AlterField(
            model_name='traceability',
            name='isolate_batch_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='N° de Lote de Aislado'),
        ),
        migrations.AlterField(
            model_name='traceability',
            name='isolate_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Aislamiento'),
        ),
    ]
