# Generated by Django 3.2.8 on 2021-10-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traceable', '0003_auto_20211028_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='traceability',
            name='received_amount',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Peso de Material Recibido (Kg)'),
        ),
    ]
